In [2]:
import pandas as pd
import numpy as np
import json

In [2]:
#https://sundararamanp.medium.com/a-relatively-faster-approach-for-reading-json-lines-file-into-pandas-dataframe-90b57353fd38
with open('./openbeta-usa-routes-aug-2020.jsonlines', 'r') as f:
    lines = f.read().splitlines()
    
df_inter = pd.DataFrame(lines)
df_inter.columns = ['json_element']
df_final = pd.json_normalize(df_inter['json_element'].apply(json.loads))

In [4]:
df_final.shape

(183253, 28)

In [6]:
df_final.columns

Index(['route_name', 'safety', 'fa', 'description', 'location', 'protection',
       'grade.YDS', 'grade.Font', 'type.boulder', 'metadata.left_right_seq',
       'metadata.parent_lnglat', 'metadata.parent_sector',
       'metadata.mp_route_id', 'metadata.mp_sector_id', 'type.tr', 'type.ice',
       'grade.French', 'grade.Ewbanks', 'grade.UIAA', 'grade.ZA',
       'grade.British', 'type.trad', 'type.sport', 'grade.yds_aid', 'type.aid',
       'type.mixed', 'type.snow', 'type.alpine'],
      dtype='object')

In [8]:
df_final.isna().sum()

route_name                      0
safety                          0
fa                              0
description                     0
location                        0
protection                      0
grade.YDS                    3499
grade.Font                 121862
type.boulder               121114
metadata.left_right_seq         0
metadata.parent_lnglat          0
metadata.parent_sector          0
metadata.mp_route_id            0
metadata.mp_sector_id           0
type.tr                    165192
type.ice                   180572
grade.French                64890
grade.Ewbanks               64890
grade.UIAA                  64890
grade.ZA                    64890
grade.British               64890
type.trad                  125327
type.sport                 125986
grade.yds_aid              181679
type.aid                   181679
type.mixed                 182161
type.snow                  182712
type.alpine                177597
dtype: int64

In [12]:
df_final['type.boulder'].value_counts(dropna=False)

NaN     121114
True     62139
Name: type.boulder, dtype: int64

In [13]:
df_final.drop(df_final[df_final['type.boulder'] == True].index, inplace=True)

In [16]:
df_final.drop(columns='type.boulder', inplace=True)

In [17]:
df_final.head()

,route_name,safety,fa,description,location,protection,grade.YDS,grade.Font,metadata.left_right_seq,metadata.parent_lnglat,...,grade.UIAA,grade.ZA,grade.British,type.trad,type.sport,grade.yds_aid,type.aid,type.mixed,type.snow,type.alpine
1,Unknown,,Unkown,[Just a general entry for the routes. Usually ...,[Can't miss the silo with a giant sheet of ice...,[No gear needed. All supplied and is Top Rope],NaN,NaN,0,"[-92.5246, 42.5484]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Stairway to Heaven,,unknown,[Climb the large flake right of Slot Machine t...,,"[SR, tricams are handy.]",5.7,NaN,5,"[-91.5625, 42.614]",...,V+,13,MVS 4b,True,NaN,NaN,NaN,NaN,NaN,NaN
4,Shagadelic Humper Bumper,,unknown,[Climb the buttress left of Cake Walk.],,[Build a TR anchor on off of trees above.],5.8,NaN,999999,"[-91.5625, 42.614]",...,VI-,15,HVS 4c,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,The Razor,,unknown,"[On the North facing wall, start at the lowest...",,[Build TR anchor on trees above.],5.8,NaN,999999,"[-91.5625, 42.614]",...,VI-,15,HVS 4c,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Cake Walk,,unknown,[Obvious chimney half way up the gully. Sever...,,[SR],Easy 5th,NaN,999999,"[-91.5625, 42.614]",...,I,5,M 1c,True,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 121114 entries, 1 to 183251
Data columns (total 27 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   route_name               121114 non-null  object
 1   safety                   121114 non-null  object
 2   fa                       121114 non-null  object
 3   description              121114 non-null  object
 4   location                 121114 non-null  object
 5   protection               121114 non-null  object
 6   grade.YDS                117615 non-null  object
 7   grade.Font               0 non-null       object
 8   metadata.left_right_seq  121114 non-null  object
 9   metadata.parent_lnglat   121114 non-null  object
 10  metadata.parent_sector   121114 non-null  object
 11  metadata.mp_route_id     121114 non-null  object
 12  metadata.mp_sector_id    121114 non-null  object
 13  type.tr                  17508 non-null   object
 14  type.ice                 2675 non-null    object
 15  grade.French             117615 non-null  object
 16  grade.Ewbanks            117615 non-null  object
 17  grade.UIAA               117615 non-null  object
 18  grade.ZA                 117615 non-null  object
 19  grade.British            117615 non-null  object
 20  type.trad                57571 non-null   object
 21  type.sport               57199 non-null   object
 22  grade.yds_aid            1565 non-null    object
 23  type.aid                 1565 non-null    object
 24  type.mixed               1085 non-null    object
 25  type.snow                536 non-null     object
 26  type.alpine              4807 non-null    object
dtypes: object(27)
memory usage: 25.9+ MB

In [20]:
df_final.loc[183250, 'description']

['A very long sport route with multiple roof pulls, a dihedral section, and lots of fun moves with great exposure.  The last bit above the final roof is quite runout, but on easy ground--keep your wits about you or bring some pro for the crack.']

In [23]:
df_final[df_final['grade.YDS'].isna()]

,route_name,safety,fa,description,location,protection,grade.YDS,grade.Font,metadata.left_right_seq,metadata.parent_lnglat,...,grade.UIAA,grade.ZA,grade.British,type.trad,type.sport,grade.yds_aid,type.aid,type.mixed,type.snow,type.alpine
1,Unknown,,Unkown,[Just a general entry for the routes. Usually ...,[Can't miss the silo with a giant sheet of ice...,[No gear needed. All supplied and is Top Rope],NaN,NaN,0,"[-92.5246, 42.5484]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
690,Left Turn,PG,Phil Patz and John Hein,[This is an aid line that follows the dihedral...,[In the corner of Hobo Cave],[Aid],NaN,NaN,8,"[-88.69184, 37.50774]",...,NaN,NaN,NaN,True,NaN,A2+ 13,True,NaN,NaN,NaN
1115,Wildcat,,unknown,"[80 foot waterfall, largest in the park., It i...",[Wildcat Canyon],[3x 50' Slings for trees and cordelette to equ...,NaN,NaN,999999,"[-88.993, 41.31768]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1151,The Virgin,,Ed Mank,[Fang in Wildcat Canyon on the left... Don't k...,[Wilcat Canyon],[TR],NaN,NaN,999999,"[-88.993, 41.31768]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1152,Totem Pole,,possibly in 1985,[NOTE: This photo included only for visual en...,[Pontiac Canyon],[toproped],NaN,NaN,999999,"[-88.993, 41.31768]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182095,AK47,,Colin Bartholomew,[This is a bolted line. I bolted it kind of li...,[Left route that pulls the roof],[bolts x4],NaN,NaN,999999,"[-120.8623, 47.8679]",...,NaN,NaN,NaN,NaN,True,NaN,NaN,True,NaN,NaN
182103,Plastic Fantastic,,unknown,"[The crux is the last pitch, but the second is...",,[Ice screws],NaN,NaN,999999,"[-120.71523, 47.59641]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
182320,Right of Hubba Hubba,,unknown,,,,NaN,NaN,2,"[-120.79239, 47.5611]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
182321,Left of Hubba Hubba,,unknown,,,,NaN,NaN,0,"[-120.79239, 47.5611]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
182335,Center Flow,,unknown,,,,NaN,NaN,1,"[-120.79239, 47.5611]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
df_final.loc[1, 'description']

['Just a general entry for the routes. Usually multiple top rope routes are set up']

In [25]:
df_final['metadata.parent_sector']

1                Silo Ice Climbing
3                    Drive In Wall
4         Cake Walk and Razor Wall
5         Cake Walk and Razor Wall
6         Cake Walk and Razor Wall
                    ...
183247              Chameleon Wall
183248                   Nut House
183249                   Nut House
183250                   Nut House
183251                   Nut House
Name: metadata.parent_sector, Length: 121114, dtype: object